### ISSUE TITLE
Crash when placing text block

### ISSUE THREAD

**Issue by LemmaEOF** [Hephaestus-Dev/glowcase#9]
https://paste.ee/p/GxFdK

discovered by quat on modfest 1.17 server

**Comment by quat1024** [comment]
I cannot reproduce this with just Glowcase (as of 6fb36249f3dc1c58aeee8d3dcd694a986382e92f) btw, even when connecting to a local server, so it's either "something in the modfest pack" or a case of "only works in-dev"

**Comment by quat1024** [comment]
A couple rounds of `filebisect` (https://github.com/comp500/filebisect) confirm it's caused by Lithium. The version in the Modfest pack is `lithium-fabric-mc1.17.1-0.7.3`.

**Comment by quat1024** [comment]
Glowcase reads directly from the `heldItem` field of `EntityShapeContext`. However, Lithium makes some of the fields in `EntityShapeContext` lazy, including `heldItem`: https://github.com/CaffeineMC/lithium-fabric/blob/1.17.x/dev/src/main/java/me/jellysquid/mods/lithium/mixin/shapes/lazy_shape_context/EntityShapeContextMixin.java
